package com.example.study.dao;

import com.example.study.entity.SysLogDO;
import org.springframework.stereotype.Repository;

@Repository
public interface SysLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Tue Jan 21 16:25:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Tue Jan 21 16:25:03 CST 2020
     */
    int insert(SysLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Tue Jan 21 16:25:03 CST 2020
     */
    int insertSelective(SysLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Tue Jan 21 16:25:03 CST 2020
     */
    SysLogDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Tue Jan 21 16:25:03 CST 2020
     */
    int updateByPrimaryKeySelective(SysLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Tue Jan 21 16:25:03 CST 2020
     */
    int updateByPrimaryKey(SysLogDO record);
}