server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapping/*.xml

#邮箱配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      #配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 10
      max-active: 20

      #配置获取连接等待超时的时间
      max-wait: 10000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000

  mail:
    host: smtp.qq.com
#    port: 465
    protocol: smtp
    username: 1321252278@qq.com
    password: obzlkwrunwkhbagh
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

    # 集成rabbitmq------------------------
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtual-host: /
      connection-timeout: 60000ms
      # 支持发布确认
      publisher-confirms: true
      # 支持发布返回
      publisher-returns: true
      cache:
        channel:
          size: 1
